### PR TITLE
Implemented DROOLS 'Fire' demo as an EasyRules demo

### PR DESCRIPTION
**Pull request by will-gilbert**
I used a bean named "TheWorld" to hold the rule engine's beans.  I couldn't anything similar in EasyRules. If this class exists, let me know and I will change the demo. "The World" is a name from Ruby Cucumber testing, sort of global, but not really in the programming language sense.  DROOLS calls its beans 'facts' and the are added directly to the rules engine.

The EasyRules 'priority' threw me.  Higher integers mean lower priority. This is opposite to DROOLS' 'salience' which is used in determining rule order execution. Rule execution was wacky until I realized this and reversed the priorities.  Then all was well.

I have to admit this is really fun and quite easy.

### CODE REVIEW

**Comment by will-gilbert** [comment]
Looks like I should have forked a fresh version of the source or somehow rebase before adding the new demo.

**Comment by benas** [comment]
> I used a bean named "TheWorld" to hold the rule engine's beans. I couldn't anything similar in EasyRules. If this class exists, let me know and I will change the demo. "The World" is a name from Ruby Cucumber testing, sort of global, but not really in the programming language sense. DROOLS calls its beans 'facts' and the are added directly to the rules engine.

Indeed, there is no such concepts in Easy rules v2, but it is coming in v3: see https://github.com/EasyRules/easyrules/issues/37

The `Facts` abstraction represents the set of facts rules will be checkecd against (and act on).

When v3 is out, I'll update tutorials accordingly. Or you can do it if you want, you are welcome!

> The EasyRules 'priority' threw me

Oh sorry for this!

>Higher integers mean lower priority. This is opposite to DROOLS' 'salience' which is used in determining rule order execution. Rule execution was wacky until I realized this and reversed the priorities. Then all was well.

Coming from the unix world, looks like I've implemented it the way "nice" command does for processes priotites. But I think as soon it is well documented (see "Rules priorities" [here](http://www.easyrules.org/user-guide/defining-rules.html)), that's fine for users.

**Comment by will-gilbert** [comment]
Nice to see 'Facts' coming to v3.  Although, 'theWorld' was just a POJO of POJOs which worked as advertised with the v2 framework and philosophy.  

The EasyRules priority scheme is fine. Once I saw how it worked I had no problems working with it.

You can either add this pull request demo to v2 or skip it and wait for v3.  I'd be happy to revise the demo for v3 and probably add some others.

**Comment by benas** [comment]
> You can either add this pull request demo to v2 or skip it and wait for v3

I'm adding this to v2. Many thanks for the updates!

> I'd be happy to revise the demo for v3 and probably add some others.

That's a great news! I will let you know when v2 is released.

Best regards
Mahmoud

**Pull request merged**
