### PR TITLE
Add Easy Rules tutorial using Groovy beans with a Gradle build

### PR DESCRIPTION
**Pull request by will-gilbert**
Mahmoud,

I think I figured out how to do a Pull Request in Github.  I created a fork of EasyRules and added a directory "easyrule-gradle" with my new code.  Hope this is correct.

BTW -- If it matters, I have no use for Spring.

### CODE REVIEW

**Comment by benas** [comment]
Hi Will,

That's fantastic! Thank you for your time and effort.

I'm merging your changes now and I'll add you to the awesome contributors list 👍 

For version 3.x, tutorials will change due to some API changes ( see #37 ), I will update your code accordingly. And I must admit, Groovy beans are awesome!

Best regards
Mahmoud

**Comment by benas** [comment]
Hi Will,

v2.6 was released and the work on v3 (major API changes) has been merged in the master branch.

I've updated all java tutorials accordingly.
I tried to do it for groovy starting with the helloworld but I'm struggling to do it. This is certainly due to the fact that I'm not comfortable with groovy and gradle.. It would be great if you can find some time to help on this. It will be much appreciated.

Important changes:

* base package changed to `org.jeasy.rules`
* hellowrorld tutorial is now the same as 'simple' tutorial
* spring and quartz tutorials have been removed

Kind regards
Mahmoud

**Comment by benas** [comment]
It's always difficult for me to ask people do things for me..

So another option is I add a link to your repo in the home page of easy rules and you can update tutorials at your own pace. What do you think?

**Comment by will-gilbert** [comment]
I'd be happy update the Groovy tutorials, especially if it frees up your time to work on V 3.0. 

I think keeping the Groovy as a seperate GitHub project is fine.  Again, it frees up your time from having to manage Pull Reqests. 

Am out of town until Monday, but look forward to jumping on this ASAP. 

I saw the Go port and am anxious to take a look at that as well.  Always want to learn som Go.

**Pull request merged**
